;;; eyespy.el --- Spy on sexps by displaying in the Messages buffer  -*- lexical-binding: t; -*-

;; Copyright (C) 2025  Michael R. Mauger

;; Author: Michael R. Mauger <michael@mauger.com>
;; Maintainer: Michael R. Mauger <michael@mauger.com>
;; Package-Type: simple
;; Package-Requires: ((emacs "29.1"))
;; Keywords: lisp, extensions, maint, tools
;; Version: 1.0.251008

;; SPDX-License-Identifier: GPL-3.0-or-later

;; This program is free software; you can redistribute it and/or modify
;; it under the terms of the GNU General Public License as published by
;; the Free Software Foundation, either version 3 of the License, or
;; (at your option) any later version.

;; This program is distributed in the hope that it will be useful,
;; but WITHOUT ANY WARRANTY; without even the implied warranty of
;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;; GNU General Public License for more details.

;; You should have received a copy of the GNU General Public License
;; along with this program.  If not, see <https://www.gnu.org/licenses/>.

;;; Commentary:

;; Although Emacs has an integrated elisp debugger, sometimes it is
;; easier to debug what is happening in a function by just displaying
;; the value of a variable in the midst of running code.  Some of us
;; are easily distracted (*cough* ADHD *cough*) and we forget what we
;; were doing between realizing that there is an error, instrumenting
;; the function for debugging, and then relaunching the failing
;; function again.  By leaving a breadcrumb in the code itself and in
;; the `*Messages*' buffer, we are reminded two days later of the
;; problem we originally encountered before we had embarked on several
;; unrelated side quests.  To minimize the impact to running code,
;; this function simply just prints the value of an expression in the
;; *Messages* buffer, and avoids pausing execution or significantly
;; interfering with display processing.  And finally, to simplify
;; identifying debugging code and messages generated by such code, the
;; macro to invoke the debugging messaging is a visible Unicode
;; character, and the messages are preceded by that character as well.

;; As an example, eyespy messaging can be invoked as follows:
;;
;;     (defun example-function (alpha beta)
;;       "This is an example of a function taking ALPHA and BETA parameters."
;;       (👀 "My system is %s" system-type)
;;       (👀 alpha beta (+ (if alpha 100 10) beta))
;;       (if alpha
;;           (+ beta 100)
;;         (👀 "Alpha is nil")
;;         (+ beta 10)))
;;
;; If the function `example-function' were invoked as follows:
;;
;;     (example-function "meaningful alpha text" 27)
;;       ⇒ 127
;;     (example-function nil 27)
;;       ⇒ 37
;;
;; the *Messages* buffer will contain:
;;
;;     👀 (example-function "meaningful alpha text" 27)  ⟼  My system is gnu/linux
;;     👀 (example-function "meaningful alpha text" 27)
;;       › alpha ⇒  "meaningful alpha text"
;;       › beta ⇒  27
;;       › (+ (if alpha 100 10) beta) ⇒  127
;;
;;     👀 (example-function nil 27)  ⟼  My system is gnu/linux
;;     👀 (example-function nil 27)
;;       › alpha ⇒  nil
;;       › beta ⇒  27
;;       › (+ (if alpha 100 10) beta) ⇒  37
;;     👀 (example-function nil 27)  ⟼  Alpha is nil
;;
;; NOTE: If the `example-function' and the calls to it above are
;; evaluated in the `*scratch*' buffer, then in place of the
;; `example-function' call with parameters, it will show "eval".  This
;; can be changed by defining the function in a local file or tweaking
;; the `eyespy-*' machinery to detect the interesting function.  For
;; example, eyespy will detect if the function is defined in a file
;; outside of the Emacs distribution or ELPA, or it can match function
;; name patterns, or the function can explicitly be defined as an
;; interesting caller by evaluating the following:
;;
;;     (eyespy-make-caller #'example-function)
;;
;; This marks the function explicitly valuable in the debugging
;; messages if encountered in the backtrace.

;; The `eyespy-message' function, which the `👀' macro invokes, has
;; the following behavior:
;;
;; + The message line will be prefixed by the macro name (i.e., 👀).
;;
;; + Following the macro name will be the calling function and it's
;; parameter's values.  (As best as can be guessed based upon
;; information in the backtrace; see the note above.)
;;
;; + There will then be an arrow to point out the message being
;; displayed or a list of values beneath it.
;;
;; + If the macro is invoked and the first parameter is a string
;; literal, then it operates the same way that `message' or `format'
;; does—the first parameter is a formatting string and the remainder
;; of the parameters as substituted into the output according to the
;; formatting rules.
;;
;; + If the first parameter to the macro is not a string literal, then
;; each parameter is formatted with the parameter text followed by
;; it's evaluated value.  Any nil literal parameters are ignored, so
;; that the first parameter can be nil to force this second style of
;; formatting.
;;
;; + The evaluated parameters of the macro are returned by the macro.
;; If there is only one evaluated parameter then it is returned
;; directly; multiple parameters are returned in a list.  Thus you can
;; surround expressions with a macro expression and it will appear in
;; the `*Messages*' buffer and will return its value to the
;; encompassing expression.  For example, below, the values of `gamma'
;; and `epsilon' will appear in the `*Messages*' buffer, but their
;; values will be passed through to the surrounding expression as if
;; the eyespy messaging wasn't present.
;;
;;     (let ((gamma 11)
;;           (epsilon  33))
;;       (+ (👀 gamma) (👀 epsilon)))
;;       ⇒ 44
;;
;; In the `*Messages*' buffer:
;;
;;     👀 eval  ⟼  gamma ⇒  11
;;     👀 eval  ⟼  epsilon ⇒  33
;;
;; The use of the eyespy icon as the macro for messaging makes
;; locating these debugging calls in code easy to find with a simple
;; `grep' command, which might be useful in git commit machinery to
;; detect debugging code in the committed bundle.  By prefixing
;; messages with the same icon makes finding them in the `*Messages*'
;; buffer simple with \\[isearch-forward] or \\[occur].

;; When you install eyespy, you can bind `eyespy-insert' in Emacs Lisp
;; source buffers to insert a macro call either around current symbol
;; or selected region.  And you can bind `eyespy-delete' to remove the
;; current or next eyespy call.  For example:
;;
;;     (define-key lisp-mode-shared-map [?\C-c ?E] #'eyespy-insert)
;;     (define-key lisp-mode-shared-map [?\C-c ?D] #'eyespy-delete)
;;
;; Now when in the `*scratch*' buffer or in an Emacs Lisp file, we can
;; insert a debugging print statement in the code fairly easily.  Based
;; on where the cursor is when `eyespy-insert' is invoked, the result is
;; shown below (point is indicated by "‸"):
;;
;;    ‸                                    ⤅  (👀 ‸)
;;    ‸abc                                 ⤅  (👀 abc)‸
;;    (abc 12‸3)                           ⤅  (abc (👀 123)‸)
;;    (abc ‸(def ghi))                     ⤅  (abc (👀 (def ghi))‸)
;;

;;; Code:

(require 'backtrace)
(require 'rx)
(require 'skeleton)

(defgroup eyespy nil
  "Display the value of elisp variables by generating messages."
  :prefix "eyespy-"
  :group 'lisp)

;; Mark functions as potential callers, or not
;;;###autoload
(defun es/make-caller (func)
  "Mark FUNC as a caller for `eyespy-caller' purposes."
  (interactive "aCaller: ")
  (put func 'es/is-caller t))

;;;###autoload
(defun es/make-not-caller (func)
  "Mark FUNC as /not/ a caller for `eyespy-caller' purposes."
  (interactive "aNot Caller: ")
  (put func 'es/is-caller nil))

(defun es/caller-p (func &optional not)
  "Is FUNC a caller, or NOT."
  (let* ((has-caller  (plist-member (symbol-plist func) 'es/is-caller))
         (caller-val  (cadr has-caller)))
    (when has-caller
      (eq caller-val (null not)))))

;; Is this function from this module
(defun es/this-is-not-the-caller (func)
  "Is FUNC part of this module?

Compare the filename sans the extension (.el, .elc, .eln).  Also check
the `eyespy-is-caller' property for special cases."
  (let ((eyespy-file (symbol-file 'es/message))
        (func-file   (symbol-file func)))
    (or (es/caller-p func :not)
        (and eyespy-file
             func-file
             (string= (file-name-sans-extension func-file)
                      (file-name-sans-extension eyespy-file))))))

;; System functions that represent evaluation so that "eval" becomes the caller
(defcustom es/eval-functions
  '( elisp--eval-last-sexp
     eval-print-last-sexp
     pp-eval-expression
     pp-eval-last-sexp )
  "Functions that indicate that the code is being explicitly evaluated."
  :type '(repeat function))

;;;###autoload
(defun es/make-eval (func)
  "Mark FUNC as an evaluator for `eyespy-caller'."
  (interactive "aEval: ")
  (push func es/eval-functions))

;; Does a function match a list of symbols, or does its name match a regexp?
(defcustom es/caller-matchers nil
  "A list of function symbols or regexp that identify calling functions."
  :type '(repeat
          (choice (string :tag "Regexp to match function name")
                  (function :tag "Matched function"))))

(defun es/-match (func matchers)
  "Internal: match FUNC to one of the MATCHERS."
  (when-let* ((this-matcher  (car matchers))
              (tail-matchers (cdr matchers)))
    (or (and (symbolp this-matcher)
             (eq func this-matcher))
        (and (stringp this-matcher)
             (string-match-p this-matcher (symbol-name func)))
        (es/-match func tail-matchers))))

(defun es/match-caller (func)
  "Does FUNC match any entries in `eyespy-caller-matchers'."
  (and es/caller-matchers
       (es/-match func es/caller-matchers)))

;; Identify functions that are not from Emacs itself
(defun es/-is-system-function (func-file-name folders)
  "Internal: Is the FUNC-FILE-NAME in any of the FOLDERS trees?"
  (when folders
    (or (string-prefix-p (car folders) func-file-name)
        (es/-is-system-function func-file-name (cdr folders)))))

(defun es/non-system-caller (func)
  "Does FUNC is not in the distribution or ELPA folder."
  (let* ((system-folders (list
                          installation-directory
                          (file-name-directory invocation-directory)
                          package-user-dir
                          (mapcar #'file-name-parent-directory package-directory-list)))
         (folder-list (delete-dups (mapcar #'expand-file-name (flatten-list system-folders))))
         (func-src (symbol-file func 'defun)))
    (and func-src ;; is not Emacs core C code
         (not (es/-is-system-function func-src folder-list)))))

(defcustom es/is-caller-functions
  '( es/caller-p
     es/match-caller
     es/non-system-caller )
  "A list of functions to decide whether the backtrace is the caller.

Each function is called with the function symbol of a back trace frame.
If a function on the list returns a non-nil, no further tests are made.
`eyespy-is-this-the-caller' is responsible for this process."
  :type '(repeat function))

(defun es/-check (func checkers)
  "Internal: check FUNC in each CHECKERS function."
  (when checkers
    (or (funcall (car checkers) func)
        (es/-check func (cdr checkers)))))

(defun es/is-this-the-caller (func)
  "Is this FUNC the likely caller of the trace function."
  (and es/is-caller-functions
       (es/-check func es/is-caller-functions)))

;; Loop through the backtrace frames looking for the caller
(defun es/caller ()
  "Display the meaningful caller."
  (interactive)
  (catch 'caller
    ;; go back thru frames starting with caller of the log function
    (dolist (frame (cdr (backtrace-get-frames)))
      (let* ((func (backtrace-frame-fun frame))
             (args (backtrace-frame-args frame)))
        (when (symbolp func)
          ;; (message "» %S: %s" (cons func args) (symbol-file func))
          (cond
           ;; ignore eyespy functions;
           ;; we can't use eyespy on eyespy...
           ((es/this-is-not-the-caller func)
            nil)
           ;; did we C-x C-e the expression
           ((memq func es/eval-functions)
            (throw 'caller 'eval))
           ;; Is function the caller
           ((es/is-this-the-caller func)
            (throw 'caller (cons func args)))))))))

;; Define the icon symbol to identify the eyespy messaging function and it's messages

;;;###autoload
(defun es/-customize-set-icon (option value)
  "Set the eyespy OPTION (icon) to VALUE, and define macro to emit a message.

To avoid duplicate messages and repeated definition of the macro, only
process if the VALUE has changed."
  (interactive "vIcon Variable (eyespy-icon): \nSValue (👀): ")
  (let ((old-value (ignore-errors
                      (default-toplevel-value option))))
    (unless (eq value old-value)
      (set-default-toplevel-value option value)
      ;; Erase the old macro; define the new one
      (when old-value
        (makunbound old-value))
      (makunbound value)
      (eval `(defmacro ,value (fmt &rest args)
               ,(format "Calls `eyespy-message' with %S and (FMT . ARGS)." value)
               (es/message (quote ,value) (cons fmt args))))
      ;; Announce the new setting
      (message "Eyespy with my little %s..." value))
    value))

(defcustom es/icon '👀
  "The function name to invoke eyespy messaging and the prefix for the message."
  :set #'es/-customize-set-icon
  :initialize #'custom-initialize-set
  :type 'symbol)
;;;###autoload (autoload '👀 "eyespy" nil nil 'macro)

;;;###autoload
(defun es/insert ()
  "Insert a call to the trace message macro.

If there is an active region, insert the region as the expression passed
to `eyespy-message'.  If there is no region, select the expression at
point instead.  If there is still no region, leave the cursor in the
`eyespy-message' call.

If a region is inserted into the call, and we're not at the end of the
line, skip forward to the next expression.

Bind this to a function key to easily insert an eyespy message."
  (interactive)
  ;; If nothing is selected, try to select the sexpr
  (unless (use-region-p)
    (when-let* ((bounds (bounds-of-thing-at-point 'sexp)))
      (push-mark (car bounds) t t)
      (goto-char (cdr bounds))))
  ;; insert the call to the macro, wrapping around the selected region
  (let (skeleton-end-newline)
    (skeleton-insert '(nil "(" (symbol-name es/icon) "\s" _ ")")
                     (when (use-region-p) -1)))
  (pop-mark)
  ;; If not at the end of the line (ignoring spaces and comments)
  (rx-let ((opt-comment-re (eval (if comment-start
                                     '(? (literal comment-start) (* nonl))
                                   ""))))
    (unless (looking-at-p (rx (* space) opt-comment-re eol))
      ;; skip forward to the next sexp
      (let ((here (point)))
        (condition-case nil
            (progn
              (forward-sexp)
              (unless (= (point) here)
                (backward-sexp)))
          (scan-error nil))))))

;;;###autoload
(defun es/delete ()
  "Remove a call to the trace message macro but leave the arguments."
  (interactive)
  ;; Move to the start of the enclosing sexp
  (when-let* ((bounds (bounds-of-thing-at-point 'sexp))
              ( (> (point) (car bounds)) ))
    (condition-case _
        (backward-up-list 1 t t)
      (t
       (goto-char (car bounds)))))
  ;; Move to the next eyespy expressions
  (when (search-forward-regexp
         (rx ?\(
             (group (* space)
                    (literal (symbol-name es/icon))
                    (+ space)))
         nil t)
    (let ((b-paren (match-beginning 0))
          (b-caller (match-beginning 1))
          (e-caller (match-end 1)))
      (delete-region b-caller e-caller)  ; delete the icon and trailing white-space
      (goto-char b-paren)
      (delete-pair))))

;; The eyespy messaging function that generates the macro code that
;; produces the actual message.
;;;###autoload
(defun es/message (icon args)
  "Display message ARGS preceded by ICON and the function name."
  ;; Generate suitable `fmt' and `args' values
  (interactive "SIcon: \nArguments: ")
  (let (fmt)
    (if (stringp (car args))
        ;; `message'-like parameters
        (setq fmt (concat "\s\s\N{Long Rightwards Arrow From Bar}\s\s" (car args))
              args (cdr args))
      ;; Each non-nil parameter has a format
      (setq args (delete nil args)
            fmt (mapconcat
                 (lambda (arg)
                   (format "%s %s %s %%S"
                           (if (= 1 (length args))
                               "\s\s\N{Long Rightwards Arrow From Bar}\s"
                             "\n\s\s\N{Single Right-Pointing Angle Quotation Mark}")
                           arg "\N{Rightwards Double Arrow}\s"))
                 args)))
    ;; Generate the macro code to message the caller and args
    (let* ((varg (gensym))
           (retval (if (cdr args) varg (list 'car varg))))
      `(let (message-truncate-lines
             print-length
             print-level
             (,varg (list ,@args)))
         (apply #'message ,(concat "%s %S" fmt)
                (quote ,icon) (es/caller) ,varg)
         ,retval))))

(provide 'eyespy)
; LocalWords:  eyespy
;;; eyespy.el ends here
;; Local Variables:
;; read-symbol-shorthands: (("es/" . "eyespy-"))
;; time-stamp-pattern: "20/Version:[\s\t]*\\(?:[[:digit:]]+[.]\\)+%y%m%d\n"
;; End:
