* Eye Spy 👀
Although Emacs has an integrated elisp debugger, sometimes it is
easier to debug what is happening in a function by just displaying the
value of a variable in the midst of running code.  Some of us are
easily distracted (/cough/ ADHD /cough/) and we forget what we were doing
between realizing that there is an error, instrumenting the function
for debugging, and then relaunching the failing function again.  By
leaving a breadcrumb in the code itself and in the `*Messages*'
buffer, we are reminded two days later of the problem we originally
encountered before we had embarked on several unrelated side quests.
To minimize the impact to running code, this function simply just
prints the value of an expression in the ~*Messages*~ buffer, and avoids
pausing execution or significantly interfering with display
processing.  And finally, to simplify identifying debugging code and
messages generated by such code, the macro to invoke the debugging
messaging is a visible Unicode character, and the messages are
preceded by that character as well.

As an example, eyespy messaging can be invoked as follows:

#+BEGIN_SRC emacs-lisp
  (defun example-function (alpha beta)
    "This is an example of a function taking ALPHA and BETA parameters."
    (👀 "My system is %s" system-type)
    (👀 alpha beta (+ (if alpha 100 10) beta))
    (if alpha
        (+ beta 100)
      (👀 "Alpha is nil")
      (+ beta 10)))
#+END_SRC

If the function ~example-function~ were invoked as follows:
#+begin_example
(example-function "meaningful alpha text" 27)
  ⇒ 127
(example-function nil 27)
  ⇒ 37
#+end_example

the ~*Messages*~ buffer will contain:
#+begin_example
👀 (example-function "meaningful alpha text" 27)  ⟼  My system is gnu/linux
👀 (example-function "meaningful alpha text" 27)
  › alpha ⇒  "meaningful alpha text"
  › beta ⇒  27
  › (+ (if alpha 100 10) beta) ⇒  127

👀 (example-function nil 27)  ⟼  My system is gnu/linux
👀 (example-function nil 27)
  › alpha ⇒  nil
  › beta ⇒  27
  › (+ (if alpha 100 10) beta) ⇒  37
👀 (example-function nil 27)  ⟼  Alpha is nil
#+end_example

If the ~example-function~ and the calls to it above are
evaluated in the ~*scratch*~ buffer, then in place of the
~example-function~ call with parameters, it will show "eval".  This
can be changed by defining the function in a local file or tweaking
the ~eyespy-*~ machinery to detect the interesting function.  For
example, eyespy will detect if the function is defined in a file
outside of the Emacs distribution or ELPA, or it can match function
name patterns, or the function can explicitly be defined as an
interesting caller by evaluating the following:
#+BEGIN_SRC emacs-lisp
  (eyespy-make-caller #'example-function)
#+END_SRC

This marks the function explicitly valuable in the debugging
messages if encountered in the backtrace.

** Installation
The ~eyespy~ package can be installed as follows:
#+BEGIN_SRC emacs-lisp
  (use-package eyespy
    :vc ( :url "https://gitlab.com/mmauger/eyespy" )
    )

#+END_SRC
** ~eyespy-message~ function (i.e., the 👀 macro command)

The ~eyespy-message~ function, which the ~👀~ macro invokes, has
the following behavior:

+ The message line will be prefixed by the macro name (i.e., 👀).

+ Following the macro name will be the calling function and it's
parameter's values.  (As best as can be guessed based upon
information in the backtrace; see the note above.)

+ There will then be an arrow to point out the message being
displayed or a list of values beneath it.

+ If the macro is invoked and the first parameter is a string
literal, then it operates the same way that ~message~ or ~format~
does—the first parameter is a formatting string and the remainder
of the parameters as substituted into the output according to the
formatting rules.

+ If the first parameter to the macro is not a string literal, then
each parameter is formatted with the parameter text followed by
it's evaluated value.  Any nil literal parameters are ignored, so
that the first parameter can be nil to force this second style of
formatting.

+ The evaluated parameters of the macro are returned by the macro.
If there is only one evaluated parameter then it is returned
directly; multiple parameters are returned in a list.  Thus you can
surround expressions with a macro expression and it will appear in
the ~*Messages*~ buffer and will return its value to the
encompassing expression.  For example, below, the values of ~gamma~
and ~epsilon~ will appear in the ~*Messages*~ buffer, but their
values will be passed through to the surrounding expression as if
the eyespy messaging wasn't present.

#+begin_example
(let ((gamma 11)
      (epsilon  33))
  (+ (👀 gamma) (👀 epsilon)))
  ⇒ 44
#+end_example

In the ~*Messages*~ buffer:
#+begin_example
👀 eval  ⟼  gamma ⇒  11
👀 eval  ⟼  epsilon ⇒  33
#+end_example

The use of the eyespy icon as the macro for messaging makes
locating these debugging calls in code easy to find with a simple
~grep~ command, which might be useful in git commit machinery to
detect debugging code in the committed bundle.  By prefixing
messages with the same icon makes finding them in the ~*Messages*~
buffer simply with [[elisp:isearch-forward][isearch-forward]] or [[elisp:occur][occur]].

** ~eyespy-insert~ to insert a 👀 macro call
When you install eyespy, you can bind ~eyespy-insert~ in Emacs Lisp
source buffers to insert a macro call either around current symbol or
selected region. For example:

#+BEGIN_SRC emacs-lisp
  (define-key lisp-mode-shared-map [?\C-c ?E] #'eyespy-insert)
#+END_SRC

Now when in the ~*scratch*~ buffer or in an Emacs lisp file, we can
insert a debugging print statement in the code fairly easily.  Based
on where the cursor is when ~eyespy-insert~ is invoked, the result is
shown below (point is indicated by "‸"):
#+begin_example
 ‸                                    ⤅  (👀 ‸)
 ‸abc                                 ⤅  (👀 abc)‸
 (abc 12‸3)                           ⤅  (abc (👀 123)‸)
 (abc ‸(def ghi))                     ⤅  (abc (👀 (def ghi))‸)
